### ISSUE TITLE
Prevent Completion of every word

### ISSUE THREAD

**Issue by guidoferreyra** [emmetio/nova-plugin#11]
**Describe the bug**
Emmet expands every word as a html tag. Not sure if its a bug but in VSCode it works differrent.

**To Reproduce**
1. Type a word like hello
2. You will see how emmet suggest a completion.
3. If you want to press return to break line it will make the completion instead of the breal

**Expected behavior**
Only make completitions for words html and not every random word.

**Environment (please complete the following information):**
 - Nova version: [e.g. 1.0.0b15]
 - Emmet extension version [e.g. 1.2.2]

**Comment by sergeche** [comment]
It’s one of the main features of Emmet: expand everything that looks like abbreviation so you don’t need predefine it first. This is especially useful if you write web-component tags or custom tags for tags for your framework. Unfortunately, the only way to expand abbreviations with Tab is to use completion provider. Limiting word subset won’t fix issue since `a` or `i` are also common words and valid abbreviations.

You can simply hit Esc to reset completion end insert line break. Alternatively, you can disable completion insertion by Enter in Nova preferences or disable Emmet auto-complete in extension preferences

**Comment by guidoferreyra** [comment]
Yes , I understand it now, thanks for the explanantion. 
I think disabling completion insertion with Enter will work for me.
