### ISSUE TITLE
Add support in .tsx for React with TypeScript

### ISSUE THREAD

**Issue by lailo** [emmetio/nova-plugin#20]
**Describe the solution you'd like**
I would like to get autocomplete while typing and correct expand for `.tsx` files which are used in React with TypeScript.

**Additional context**
Currently, there is no autocomplete popup while typing in `.tsx` nor the JavaScript version of it `.jsx`.
If I use the *Expand Abbreviation*, I get `class="..."` instead of `className="..."` in `.tsx` files.  In a `.jsx` file the `className="..."` works fine.

Thanks for helping.

**Comment by sergeche** [comment]
Should be fixed in v1.3.0

**Comment by eivindml** [comment]
Hi, this is still a issue for me, using `v1.3.1`. 

`Foo.Bar` is expanded into `<Foo className="Bar"></Foo>`, and `div.test` is expanded into `<div class="test"></div>`.

**Comment by cora-type** [comment]
I may be missing something here but autocomplete does not seem to work in .tsx files still

**Comment by sergeche** [comment]
@cora-type seems to be broken due to latest changes in Nova. Just pushed v1.3.5 that should work with TS.

Note that by default in JSX syntaxes it’s required to prefix abbreviation with `<`
<img width="368" alt="image" src="https://user-images.githubusercontent.com/93595/228357246-d20037e0-9e46-4bab-b8ef-995775b3f393.png">

**Comment by cora-type** [comment]
Works great now, thanks!

**Comment by eivindml** [comment]
Hmm. I'm still not getting the `className` completion in `.tsx` files. Using `ctrl + e`.
