### ISSUE TITLE
I am still seeing issues in scss files (attached) and html in php files is spotty.

### ISSUE THREAD

**Issue by tomliv** [emmetio/nova-plugin#8]
I am still seeing issues in scss files (attached) and html in php files is spotty.

![CleanShot 2020-05-29 at 14 04 45](https://user-images.githubusercontent.com/1153953/83291124-d43ad780-a1b5-11ea-99bf-6965bb5a448c.gif)

_Originally posted by @tomliv in https://github.com/emmetio/nova-plugin/issues/6#issuecomment-636110837_

**Comment by sergeche** [comment]
This is the expected behaviour. Emmet works with snippets, not real CSS properties. So, when you type `marg`, it can’t find any [snippet](https://github.com/emmetio/emmet/blob/master/snippets/css.json) for it so it provided fallback with `marg: ;`.

Same with `margin-top`: the `-` character is used to separate values in Emmet abbreviation (like `m10-20` produces `margin: 10px 20px`, `h-a` produces `height: auto`) so it gave you `margin: top`. It’s rather useless to type full property names and use Emmet to insert `: ;` for you, while there are snippets like `mt` to get `margin-top`.

**Comment by tomliv** [comment]
I see. I've apparently mistaken Emmet for some other helper - albeit built-in or add-on. Thanks.

**Comment by sergeche** [comment]
It should be handled by standard Nova completions, like in CSS. That’s why Emmet acts as completion provider so you can pick desired snippet from completion popup. In previous versions, Emmet hijacks Tab key so it becomes the only option for completion  

Отправлено с iPhone

**Comment by tomliv** [comment]
Thanks. I am used to VS Code. It makes suggestions that I use a lot. In scss, html, html in php, php... I think it's built-in. I guess I am looking for a more robust equivalent in Nova.
